openapi: 3.0.0
info:
  title: Sample API
  version: 1.1.0
paths:
  /users:
    get:
      summary: Get users
      responses:
        '200':
          description: OK
    post:
      summary: Create user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: integer
                name:
                  type: string
                age:
                  type: integer
      responses:
        '201':
          description: User created
  /items:
    delete:
      summary: Delete item
      responses:
        '200':
          description: OK
